Create setup docs and basic contributions guidelines
FOSSUChennai/Communities pull request #11
Opened 2024-12-31 17:36 UTC by hareesh-r

2024-12-31 17:41 UTC, JustinBenito requested changes
emphasize more on how to add events to json will be a great addition to contributing.md
Please look into it

A bit more context over tamilnadu.tech instead of focusing on the tech stack will help a lot. Adding the tech stack at the end and explaining about the app and the reason behind it and why people should contribute and how easy it is to contribute are some of the key things to add here. 
Please do look into it aswell. 


Awaiting an updated PR. 

Cheers :)

2024-12-31 18:08 UTC, hareesh-r commented
Updated Docs on emphasizing contribution

2025-01-01 05:14 UTC, JustinBenito requested changes

2025-01-01 05:14 UTC, JustinBenito commented on CONTRIBUTING.md
> +By contributing, you agree that your contributions will be licensed under the MIT License.
Please do change it to GPL 3.0 License 😅

2025-01-01 05:14 UTC, JustinBenito commented on README.md
> +This project is licensed under the terms of the MIT license.
Please do change it to GPL 3.0 License

2025-01-01 05:26 UTC, JustinBenito commented on src/app/events.tsx
> +    const EventCard: React.FC<EventCardProps> = ({ communityname, title, date, location, venue, link, logo }) => {
Looks amazing as a special effect, would be really great if we could hide the gray border onHover and then have this effect so that both of those borders dont stack up. 

This is minor and can be solved in another PR too, but just putting this in

2025-01-01 06:29 UTC, JustinBenito approved these changes
lgtm 🥳

2025-01-01 06:29 UTC, merged